### ISSUE TITLE
Cannot bulk load. The bulk data stream was incorrectly specified as sorted or the data violates a uniqueness constraint imposed by the target table.

### ISSUE THREAD

**Issue by gavindew** [yorek/smartbulkcopy#17]
I consistently cannot get this to work on a one of my large partitioned tables. I created the target schema (partition function and scheme) by scripting the source, so its identical.

However, when running the copy, I get the following error:
Cannot bulk load. The bulk data stream was incorrectly specified as sorted or the data violates a uniqueness constraint imposed by the target table. Sort order incorrect for the following two rows: primary key of first row: (2016-11-06, 8406347, 20), primary key of second row: (2016-11-02, 8406348, 1)

Everything looks good from the INFO logs:

Source and destination tables have compatible partitioning logic. Parallel load available
Partition By: Date
Order By: TransactionId,CategoryId
Source and destination clustered rowstore index have same ordering. Enabling ORDER hint.
Parallel load will use 18 physical partition(s)
Analysis result: usePartioning=True, partitionType=Physical, orderHintType=ClusteredIndex

Any ideas ?

**Comment by gavindew** [comment]
Ok, so the issue seems to be caused by this:
public string GetOrderBy()
{           
      return SourceTableInfo.PrimaryIndex.GetOrderBy(excludePartitionColumn:**true**);
}

This means the ORDER BY generated in the SELECT statement excludes the partitioning key, but the ORDER BY added to the BulkCopy itself includes the  partitioning key. When I change excludePartitionColumn to false, it works fine.

**Comment by yorek** [comment]
Good catch, thanks! Not sure I understand what are the conditions that make this issue happen. You have the table on source and the destination created with the same partitioning function and scheme. Both have an Clustered Index.
Adding the Partition column to the order by is needed to make sure sorting does not happen on the destination.
Are you able to create a repro so that I can take a look at it?
Thanks!

**Comment by gavin-eq** [comment]
This script should highlight the issue: By excluding the partition column, the sort order of the data will be different on select and in bulk copy object.

CREATE PARTITION FUNCTION [pfTest](date) AS RANGE LEFT FOR VALUES (N'2018-12-31T00:00:00.000', N'2019-12-31T00:00:00.000')
GO
CREATE PARTITION SCHEME [psTest] AS PARTITION [pfTest] TO ([PRIMARY], [PRIMARY], [PRIMARY])
GO
CREATE TABLE PartitionTest (
	PartitionDate date not null,
	TransactionId int not null,
	CategoryId int not null
	CONSTRAINT [PK_PartitionTest] PRIMARY KEY CLUSTERED 
	(
		PartitionDate ASC,
		TransactionId ASC,
		CategoryId ASC
	) ON [psTest]([PartitionDate])
)
GO
INSERT INTO PartitionTest (PartitionDate, TransactionId, CategoryId) 
VALUES
('2018-01-01', 2, 1),
('2018-01-02', 1, 1)

**Comment by yorek** [comment]
Thanks, will take a look ASAP

**Comment by yorek** [comment]
Thanks, I was able to repro the problem and fixed it. Added also unit tests and CI/CD pipeline to make sure not to introduce regression bugs.
Fixed here: b85f6b820c912d9160277f6270e2b938e35d127c
